### ISSUE TITLE
Spaces in 'program' not properly escaped

### ISSUE THREAD

**Issue by thejustinwalsh** [vshaxe/flash-debugger#17]
If there are spaces in your path to the .swf that you are launching, the debugger will just open a command prompt.

Issue is present on Windows, have not tested other operating systems.

_Workaround_: `Do not use a path with spaces in it`.

**Comment by thejustinwalsh** [comment]
Looks like the [C# debug adapter](https://github.com/OmniSharp/omnisharp-vscode/issues/184) had the same problem once upon a time.

**Comment by Gama11** [comment]
Hm.. I actually can't seem to reproduce this, the following works fine:

```json
"program": "${workspaceRoot}/export/fla sh/bin/Mo de.swf"
```

I'm on Windows 10.

**Comment by thejustinwalsh** [comment]
Haven't tried it recently. Maybe the way the process was being launched was fixed in VS Code itself?

**Comment by Gama11** [comment]
Seems unlikely, I think this is done by the flash debugger.
