### ISSUE TITLE
$1000 bounty for integrated/testing/actually-works C++ debugging

### ISSUE THREAD

**Issue by larsiusprime** [vshaxe/flash-debugger#9]
"Support for the C++ target via hxcpp-debugger is planned."

I'm willing to put my money where my mouth is. I'm happy to put $1,000.00 USD towards the completion of this feature, payable by Level Up Labs, LLC. If multiple people wind up collaborating on it, I'm happy to split the bounty among the contributors.

This would be well worth the investment as the lack of well supported, IDE-integrated C++ debugging is the no. 1 drag on my daily productivity and also one of the major features holding back wider haxe adoption by newcomers.

**Comment by Jarrio** [comment]
Just to mention had a pretty good working haxe c++ debugger so maybe he would be interested in helping with this. [C++ debugger](https://github.com/jcward/vscode-hxcpp-debug)

**Comment by nulld** [comment]
C++ target is already inprogress. I'm going to push the draft version this weekend. And it will be super, if someone can join to me with evolving it, cause I don't have enough free time at the moment but I need propertly working C++ debugger too.

**Comment by nulld** [comment]
For now, I'm stucked with this problem. https://github.com/HaxeFoundation/hxcpp-debugger/issues/17

**Comment by jcward** [comment]
@nulld - I'm seeing that Hugh's newly released hxcpp 3.4.64 has resolved the issue with breakpoints. Maybe try again?

**Comment by jcward** [comment]
FYI, Hugh resolved another issue wrt the "step over" function of the debugger, in 3.4.69 available in the [hxcpp nightlies](http://nmehost.com/hxcpp/).

**Comment by nulld** [comment]
@jcward Thanks, yes this works now.

**Comment by Gama11** [comment]
https://github.com/vshaxe/hxcpp-debugger is now available on the VSCode marketplace: 

- https://marketplace.visualstudio.com/items?itemName=vshaxe.hxcpp-debugger

All credit for this one goes to @nulld. :)

**Comment by larsiusprime** [comment]
Huzzah! Email me at lars dot doucet at gmail to claim your reward, @nulld.

**Comment by nulld** [comment]
@larsiusprime, got it, thank you.
